[book]
authors = ["Torsten Dittmann"]
language = "en"
multilingual = false
src = "src"
title = "GustavPHP"

[output.html]
mathjax-support = false
site-url = "/mdBook/"
git-repository-url = "https://github.com/gustav-php/gustav"
edit-url-template = "https://github.com/gustav-php/gustav-php.github.io/edit/main/{path}"